### PR TITLE
Some video players with drm protection need the HW Overlay

### PR DESCRIPTION
**Pull request by halfluck**
Could this help?

### CODE REVIEW

**Comment by mknrls** [comment]
@halfluck this might work but we worry about it for now. Its not the biggest issue is at the moment.

**Comment by halfluck** [comment]
No worries, maybe the wildvine drm stuff needs to be added too for netflix.

**Comment by npjohnson** [comment]
I'm in the process of testing this. If it helps get YT/Netflix going, I'll merge it

**Comment by halfluck** [comment]
Cool, A new build of Netflix for Android TV was released this morning ==> http://www.apkmirror.com/apk/netflix-inc/netflix-for-android-tv/netflix-android-tv-2-2-1-build-643-android-apk-download/

**Comment by halfluck** [comment]
the original ADT-1 build.prop has this too ==>

ro.com.widevine.cachesize=16777216

**Comment by r3pwn** [comment]
I'll test these out tomorrow and see how it goes.

**Comment by r3pwn** [comment]
So, I checked: the ro.sf.hw prop didn't help, and we already have the ro.com.widevine.cachesize prop in the build.prop

**Pull request closed without merging**
